/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class engineadapter_EngineAdapter */

#ifndef _Included_engineadapter_EngineAdapter
#define _Included_engineadapter_EngineAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     engineadapter_EngineAdapter
 * Method:    start
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jstring JNICALL Java_engineadapter_EngineAdapter_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     engineadapter_EngineAdapter
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_engineadapter_EngineAdapter_stop
  (JNIEnv *, jobject);

/*
 * Class:     engineadapter_EngineAdapter
 * Method:    write
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_engineadapter_EngineAdapter_write
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_engineadapter_EngineAdapter_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
